/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: gaoran0623 (https://sketchfab.com/gaoran0623)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/panda-head-meme-726745400b4d44128016f4280c313a3d
Title: Panda head meme
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useMotionValue, useSpring } from "motion/react";
import { useFrame } from "@react-three/fiber";

export function Astronaut(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/panda_head_meme.glb");

  const yPosition = useMotionValue(5);
  const ySpring = useSpring(yPosition, { damping: 30 });
  useEffect(() => {
    ySpring.set(-1);
  }, [ySpring]);
  useFrame(() => {
    group.current.position.y = ySpring.get();
  });

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      rotation={[0, 0, 0.25]}
      scale={props.scale || 2}
      position={props.position || [1.3, -1, 0]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials["Material.001"]}
        position={[0.053, 0.022, 0]}
        rotation={[3.031, 0, Math.PI]}
        scale={0.844}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.black}
        position={[0, -0.804, -0.826]}
        rotation={[0.151, 0, 0]}
        scale={[1.366, 1.507, 1.252]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.black}
        position={[-0.113, 0.354, 0.333]}
        scale={0.031}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.black}
        position={[0.235, 0.344, 0.329]}
        scale={0.032}
      />
    </group>
  );
}

useGLTF.preload("/models/panda_head_meme.glb");
